#! /bin/sh
#
# This configure script is *not* autoconf-based and has different semantics.
#
# Some code borrowed/learned from MPlayer's script
#

# Prevent locale nonsense from breaking basic text processing utilities
export LC_ALL=C

# Extract revision number from snapshot_version, then 'svn info'. If both fail, "UNKNOWN"
# Used only for compiled binary directory
svn_revision=$(cat snapshot_version 2> /dev/null)
test $svn_revision || svn_revision=$(LC_ALL=C svn info 2> /dev/null | grep Revision | cut -d' ' -f2)
test $svn_revision || svn_revision=UNKNOWN
version=$svn_revision

# Default configure options
default_opts="--enable-static --enable-runtime-cpudetection --disable-libmpeg2-internal --disable-tv --disable-vidix --disable-faac-lavc"

# Default options
_debug=no
_dryrun=no
_build_mencoder=yes
_build_mplayer=yes
_prefix="/usr/local"

for ac_option do
  case "$ac_option" in
  --help|-help|-h)
    show_help
    ;;
  --prefix=*)
    _prefix=$(echo $ac_option | cut -d '=' -f 2)
    ;;
  --nomake-mencoder)   _build_mencoder=no    ;;
  --nomake-mplayer)    _build_mplayer=no     ;;
  --make-debug)    _debug=yes     ;;
  --dry-run)    _dryrun=yes     ;;

  *)
    echo "Unknown parameter: $ac_option"
    exit 1
    ;;

  esac
done


# Functions
show_help(){
cat << EOF
Usage: $0 [OPTIONS]...

Configuration:
  -h, --help             display this help and exit

Installation directories:
  --prefix=DIR           prefix directory for installation [/usr/local]

Optional features:
  --nomake-mencoder     disable MEncoder (A/V encoder) compilation [enable]
  --nomake-mplayer      disable MPlayer compilation [enable]
  --make-debug          compile-in debugging information (level 3) [disable]
  --dry-run             run configure but do not start compile

NOTE: These options are similar to mplayer's configure script but do not mean
the same thing! The mplayer and mencoder executables are compiled separately,
with --disable-mencoder used during mplayer compilation to reduce the binary
size of mplayer.

This script is intended to automate building mplayer and/or mencoder using
the same options that I use. Executables will be placed by default in 
/usr/local/mpl-bin-r(REVISION) but can be customized by using --prefix.
Prefix paths must not contain colons. Windows paths must be written like so:

  /c/Projects/mplayer

EOF
exit 0
} #show_help()

run_makeclean(){
if test -e config.mak ; then
  make distclean
fi
}

make_instdir(){
if test ! -d "$install_dir" ; then
  mkdir "$install_dir"
fi
}


# Prepare diretory name
if test "$_debug" = yes ; then
  debug_opts="--enable-debug=3"
  debug_bin_suffix1="-d"
  debug_bin_suffix2="d-"
fi

# Check if mpl-bin-r(REVISION) exists, if it does, append a number
# and increment it until a directory with the appended number isn't
# found and use that.
if test -d "$_prefix/mpl-bin-r$version$debug_bin_suffix1" ; then
  count=2
  while [ 2 ]
  do
          if [ ! -d $_prefix/mpl-bin-r$version-"$debug_bin_suffix2$count" ] ; then
              install_dir=$_prefix/mpl-bin-r$version-"$debug_bin_suffix2$count"
              break
          fi
          count=$[count+1]
  done
else
  install_dir=$_prefix/mpl-bin-r$version$debug_bin_suffix1
fi


# Compile MPlayer
if test "$_build_mplayer" = yes ; then

  run_makeclean
  ./configure $default_opts --disable-mencoder $debug_opts
  if test "$_dryrun" = yes ; then
    exit
  else
    ./build_fixes --replace-decoders
    make
  fi

  set -x

  if ! test -e mplayer.exe ; then
    echo "MPlayer executable not found. Something went wrong."
    exit 1
  fi

  make_instdir

  if test "$_debug" = yes ; then
    cp mplayer.exe $install_dir/mplayer.exe.debug
  else
    strip -s mplayer.exe -o $install_dir/mplayer.exe
  fi

  set +x

fi

# Compile MEncoder
if test "$_build_mencoder" = yes ; then

  run_makeclean
  ./configure $default_opts --disable-mplayer $debug_opts
  if test "$_dryrun" = yes ; then
    exit
  else
    ./build_fixes --replace-decoders --replace-encoders
    make
  fi

  set -x

  if ! test -e mencoder.exe ; then
    echo "MEncoder executable not found. Something went wrong."
    exit 1
  fi

  make_instdir

  if test "$_debug" = yes ; then
    cp mencoder.exe $install_dir/mencoder.exe.debug
  else
    strip -s mencoder.exe -o $install_dir/mencoder.exe
  fi

  set +x

fi

run_makeclean
